### PR TITLE
Added "Random MVP" option in menu.

### PR DESCRIPTION
**Pull request by kratos1812**
Now players can select to have a random MVP Anthem every round via the menu.
As requested by https://forums.alliedmods.net/showpost.php?p=2755377&postcount=138

### CODE REVIEW

**Comment by No-Death** [comment]
Hello @kratos1812! 
I tried this, seems like the volume is broken. Volume 0 works but everything else seems to be 100. Can you take a look? :)

**Comment by kratos1812** [comment]
> Hello @kratos1812!
> I tried this, seems like the volume is broken. Volume 0 works but everything else seems to be 100. Can you take a look? :)

Hi, @No-Death 
The official branch works good? I suspect this might not be related to my fork. I have to look more into it, I didn't have the time today.

**Comment by No-Death** [comment]
> > Hello @kratos1812!
> > I tried this, seems like the volume is broken. Volume 0 works but everything else seems to be 100. Can you take a look? :)
> 
> Hi, @No-Death
> The official branch works good? I suspect this might not be related to my fork. I have to look more into it, I didn't have the time today.

I may have been wrong, I was in a hurry when I checked and my players complained about the volume. Seems like it may have been the sound that was used that just was loud. I will try again, sorry.

**Comment by rogeraabbccdd** [comment]
LGTM, thanks.

**Comment by crashzk** [comment]
**@kratos1812** just feedback on this update.

**Random MVP** option allows players even without privileges or access to MVP to choose this option. Even if there is no sound available for these unprivileged players, the plugin still shows on the screen if it is MVP if it chooses the random option.

https://github.com/rogeraabbccdd/CSGO-MVP/issues/28

**Pull request merged**
